echo off
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 1 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 2 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 3 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 4 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 5 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 6 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 7 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 8 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 9 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 10 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 11 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 12 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 13 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 14 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 15 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 16 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 17 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 18 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 19 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 20 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 21 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 22 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 23 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 24 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 25 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 26 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 27 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 28 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 29 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 30 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 31 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 32 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 33 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 34 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 35 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 36 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 37 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 38 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 39 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 40 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 41 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 42 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 43 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 44 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 45 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 46 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 47 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 48 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 49 -n 1000
java -jar .\out\artifacts\EpidemicSimulation_jar\EpidemicSimulation.jar -cp 50 -n 1000
